Algorithm-study-s10/Algorithm_Study

src/main/java/org/example/yhs3237/TwoPointer.java

투포인터 기법 문제 풀이 (테스트 PR)

---

src/main/java/org/example/seonmin98/nnArray.java

n^2 배열 자르기-선민

---

.idea/gradle.xml
.idea/misc.xml
.idea/vcs.xml
src/main/java/org/example/yhs3237/n2Array.java

n^2 배열 자르기-혜선

---

src/main/java/org/example/yhs3237/w01_arrayRotation/baekjoon16926.java
src/main/java/org/example/yhs3237/w01_n2Array/n2Array.java

https://www.acmicpc.net/problem/16926
- 행렬을 2차원 배열에 넣음
- 처음엔 단순히 바깥쪽과 안쪽을 나누어 세로 이동의 경우 행 좌표를, 가로 이동의 경우에는 열 좌표를 변화시키면서 이동한다고 생각 => 방향 전환 문제에 부딪힘
- 달팽이 문제와 유사하다고 생각하여 배열 끝에 도달하면 방향을 변경하는 방안 생각 => 좌표 값을 어떻게 옮겨야할지에 대한 문제
- 결국 첫번째 값(제일 바깥쪽의 경우 [0][0])을 따로 빼두고, 해당 칸을 빈칸이라고 생각하여 맨 윗줄부터 배열을 미는 방법 생각 (배열 미는 순서 : 위 가로, 오른쪽 세로, 아래 가로, 왼쪽 세로)
- 마지막에 빼둔 값을 빈칸([1][0])에 넣어주면 정렬 완료
> 배열을 밀 때, for문을 사용하면서 범위 설정과 좌표 값 설정에 많은 시간이 걸렸는데 이걸 좀 더 빠르게 구할 수 있는 좋은 방법이 있을까요? 아니면 좌표 값을 덜 복잡하게 설정하는 방법이 있을까요?

w01_배열돌리기 - 혜선

---

src/main/java/org/example/yhs3237/w02_paperAttach/baekjoon17136.java

https://www.acmicpc.net/problem/17136
1) 좌표 탐색하면서 1이 나오면 5X5부터 1X1까지 붙일 수 있는지 탐색
- 해당 크기 색종이 붙일 수 있으면 해당 좌표값을 1->0 
- 재귀 호출 (y 좌표 + 1)
- 색종이 다시 떼기 (백트래킹) ==> 최적 해를 구하기 위해 모든 경우를 탐색
2) 해당 크기 색종이 붙일 수 없으면(좌표값이 0이면) 다음 좌표로 넘어감
! point : 각 색종이의 개수가 5개이므로 사용한 색종이의 개수를 관리해주어야 함 (따로 배열 선언) 
> 사실 백트래킹 구조를 약간 외워서 푼 경향이 있어서 아직 백트래킹 구조가 잘 이해되지 않습니다...ㅠ
그리고 추가로 처음 문제를 접했을 때, 이걸 백트래킹으로 풀어야하는지 아닌지를 어떻게 판단해야 할까요?

w02_색종이붙이기 - 혜선

---

src/main/java/org/example/yhs3237/w02_topStack/beakjoon2493.java

https://www.acmicpc.net/problem/2493
1) N의 크기가 500000 
-> 스택에 데이터를 모두 넣지 않고, 조건에 따라 pop, push하여 많은 데이터가 스택에 쌓이지 않도록 함
-> 스택이 비어있다면 무조건 push하고 0 출력
-> 스택에 있는 탑의 높이가 입력받은 탑의 높이보다 낮으면 pop (높은 탑이 나올때까지 반복)
-> 높은 탑을 만나면 해당 탑의 높이를 반환하고 입력받은 탑 push
2) top의 정보 2가지를 어떻게 처리할 것인가?
-> top 정보를 담는 클래스를 생성하여 탑의 번호와 높이 담음
-> 탑의 높이 입력 받을 때마다 새로운 top 생성하여 탑의 번호(i)와 높이(입력받음)를 저장
-> 저장하는 값을 top으로 하는 스택 생성
> top 클래스를 만들지 않고 처리하는 방법이 있을까요? 그리고 시간을 더 줄일 수 있는 방법이 있을지도 함께 고민해보아요~

w02_탑 - 혜선

---

src/main/java/org/example/iroo2001/w02_탑/Main.java
src/main/java/org/example/iroo2001/w02_탑/Main2.java

[백준 2493번 : 탑](https://www.acmicpc.net/problem/2493)
* 입력을 받는 동시에 동작 수행
* int[] nums : 입력받은 수를 저장하는 배열
* stack : 탑의 번호를 저장하는 스택 (index를 저장)
0. i=0 ~ n-1까지 for 문 돌리며 수행
1. 현재 입력받은 수를, nums[i]에 저장함
2. 스택이 비어있는지 검사
i) 비어있지 않은 경우
- 스택의 마지막 값(index)을 활용하여, nums[index]가 현재 탑보다 높은지 확인
- 현재 탑보다 높은 경우, index+1을 출력
- 현재 탑보다 높지 않은 경우, 높아질 때까지 stack.pop()하여 다음 값 확인
ii) 원래 비어있거나, 위 단계를 스택이 비워질 때까지 했음에도 높은 탑이 없는 경우
- 무조건 0을 출력
- 스택에 현재 index 저장
> boolean flag 변수를 활용하여 나보다 높은 탑을 찾았는지 체크했는데, flag를 사용하지 않고 할 수 있을까요?

w02_탑 - 이루

---

src/main/java/org/example/rt8632/w02_Top/boj_2493.java

https://www.acmicpc.net/problem/2493
- 처음에 스택에 모조리 집어넣고 하나씩 빼서 확인하는 방법을 시도했었는데, 아무리 생각해봐도 접근 방식이 잘못된 것 같아서 풀이 보고 풀었습니다.... 나중에 다시 풀어볼게요
- 그리고 처음에 scanner 썼는데 그럼 시간 초과 난다고 해서 bufferreader로 바꿨습니다
- 풀이를 보고 로직을 이해한 바로는 초기 스택이 비어있는 경우 무조건 0을 출력하게 하고, 그 이후부터는 반복문 내부 조건에 따라 판단하도록 하고 있습니다. 스택에 있는 탑의 높이가 현재 탑의 높이보다 높으면 해당 탑의 번호를 추가하고 스택에 해당 탑을 추가합니다. 만약 낮은 경우 pop 연산을 통해 스택 최상위의 탑을 제거합니다. 마찬가지로 이때 스택이 비어있게 되는 경우 0을 출력하도록 합니다. 
- 꼭 Top 클래스를 생성하지 않고도 풀 수 있는 방법이 있을까요?
- 그리고 뭔가 문제에서 해결방법이 잘 생각이 안날때는 어떻게 접근하는게 좋은지 궁금합니다. 너무 무작정 풀이를 보는 것 같기도 해서요ㅜㅜ

w02_탑 - 예린

---

src/main/java/org/example/seonmin98/w02_탑/Main.java

https://www.acmicpc.net/problem/2493
- 첫 시도 (메모리 초과)
1. 일단 입력받으면서 스택에 다 넣어놓기
2. 하나씩 pop 하면서 현재보다 높은 거 나올 때 까지 pop
2 - 1. pop 한 거 tmp 저장해놓고 다시 push....^^
3. 높은 거 찾으면 ret 에 추가...ㅎㅎ
- 두 번째 시도 (시간 초과)
: 첫 시도와 로직은 비슷하나 tmp 에 빼두는 게 아니라 인덱스로 순회하면서 값 비교
- 세 번째 시도 (시간 초과
: 마찬가지로 로직은 비슷한데 입력 받으면서 계산
- 네 번째 시도 (마참내 정답)
: 입력 받으면서 바로 계산 + 인덱스도 같이 쌍으로 넣어서 필요 없으면 바로 pop
> 코드가 점점 발전해나가는 건 좋은데... 처음부터 정답을 떠올리기엔 아직 한계가 있네요... 점점 빠르게 접근할 수 있겠죠...??ㅠㅠ

w02_탑 - 선민

---

src/main/java/org/example/seonmin98/w02_프린터큐/Main.java

https://www.acmicpc.net/problem/1966
주석으로 대체하겠습니다..

w02_프린터큐 - 선민

---

src/main/java/org/example/jayji5204/w02_Queue/Main_SH.java

https://www.acmicpc.net/problem/1966
처음에는 중요도 따로 인덱스 따로 계산해서 하려고 하니 복잡하고 중복이 되었을 때 해결이 되지 않았습니다.
그러다가 저번에 풀었을 때 배열을 담아서 하는 것이 생각이 나서 배열에 인덱스와 중요도를 함께 담아서 처리를 하였습니다.

w02_프린터큐- 성현

---

src/main/java/org/example/rt8632/w03_PrinterQueue/boj_1966.java

https://www.acmicpc.net/problem/1966
- 이 문제를 몇년전에 시도했다가 우선순위 큐를 써야한다고 해서 포기했었는데, 이번에도 쓰려고 시도하다가 어떻게 쓰는지 몰라서 그냥 큐를 썼습니다....
- 커스텀 클래스 쓰려다가 너무 복잡해질 것 같아서 그냥 큐에 int형의 배열을 넣고 인덱스 0에는 위치, 인덱스 1에는 중요도를 넣어서 구현했는데 나쁘지 않은 방법인 것 같습니다.
+잘못해서 뭔가... 처음보는 사람의 계정으로 main에 푸시가 되어버렸는데 무시해주세요 흑흑 저거 돌리고 싶은데 어케 돌리는지를 모르겠습니다 애초에 왜 저 계정으로 올라갔는지도 모르겠어요 예전에 이 컴퓨터를 사용한 적이 있는 계정인가봐요......
- 정석적인 풀이는 우선순위 큐를 사용하는 방법인 것 같은데 어떻게 쓰는 건지 궁금합니다

w03_프린터큐 - 예린

---

src/main/java/org/example/yhs3237/w03_cardDeque/baekjoon20923.java

https://www.acmicpc.net/problem/20923
단순하게 각 플레이어의 카드 덱과 그라운드 덱을 만들었습니다.
그리고 각 플레이어의 차례마다 
1) 카드 덱에서 카드를 뽑아(pollLast) 그라운드 덱에 놓음(addLast)
2) 카드 덱이 비었는지 확인 (비었다면 break, 상대방이 승리)
3) 카드 덱에서 뽑아 그라운드 덱에 놓은 카드가 5인지 확인 (peekLast)
4) 그라운드 덱에 있는 카드의 합이 5인지 확인 (peekLast)
5) 위 조건에 부합한다면 승리한 플레이어의 카드 덱의 아래에 그라운드 덱에 있는 카드들 추가 (pollFirst -> addFirst)
위 과정을 반복하였습니다.
각 플레이어가 카드를 한장 뽑을 때마다 게임의 횟수가 1이 된다는 점이 포인트!
그래서 M번 반복하되, 짝수번째에는 도도가 홀수번째에는 수연이가 플레이하도록 작성했습니다.
눈물의 제출 이력,.,,,,
> 덱을 이렇게 많이 만드는 게 맞는지...

w03_숫자 할리갈리 게임 - 혜선

---

src/main/java/org/example/seonmin98/w03_숫자할리갈리/Main.java

https://www.acmicpc.net/problem/20923
1. 둘다 한번씩 놓는 게 1턴이라고 오해함
2. 종을 한번 쳐야지 1번 진행한 거라고 오해함
3. 집어넣고 빼는 순서가 엉망진창이었음.....
로직은 아마 대부분 비슷할 것으로 예상됩니다
> 덱 뭔가 처음 써보는 것 같은데 원래 이렇게 헷갈리는 게 맞나요......ㅠㅠ

w03_숫자 할리갈리 게임 - 선민

---

src/main/java/org/example/seonmin98/w03_연산자끼워넣기/Main.java

https://www.acmicpc.net/problem/14888
수의 순서 고정 + 우선순위 고려 X + int 범위 내의 값 => 굉장히 친절한 문제 👍 
연산자를 배열이나 스트링으로 관리해볼까 했는데 헷갈려질 것 같아서 그냥 직관적이게 각각의 변수로 관리하는 방법을 택했습니다!
재귀로 돌면서 연산이 끝나면 min, max 값을 갱신해주었습니다!
-> 연산의 순서가 정해져있는 것이 아니라 조건문으로 카운트값을 계속 갱신해주면서 재귀를 돌렸어요
지난번 a형 문제 유형과 비슷한 문제였던 것 같습니다 ~
> 이처럼 비슷하면서도 똑같은 로직이 반복될 때 배열이나 함수로 묶어서 관리하는 게 좋을까요? 아니면 조금은 무식해보일 수 있지만 직관적이게 작성하는 게 베스트일까요? 다른 분들의 의견이 궁금합니다

w03_연산자 끼워넣기 - 선민

---

.idea/gradle.xml
.idea/uiDesigner.xml
src/main/java/org/example/yhs3237/w03_addOperator/Main.java
src/main/java/org/example/yhs3237/w03_addOperator/baekjoon14888.java

https://www.acmicpc.net/problem/14888
✅연산자 관리
재귀 로직을 만들고 가장 고민이었던 부분이 "연산자들을 어떻게 관리할 것인가?" 였습니다.
연산자들을 스택으로 관리할지, 배열로 관리할지 고민했는데 스택은 좀 정신이 없는 느낌이라 숫자들과 연산자들을 각각 배열로 관리해주었습니다.
연산자의 경우에는 operations 배열로 관리했고, 인덱스 0부터 3까지 차례로 +, -, *, / 연산을 의미합니다.
✅재귀
숫자는 고정되어있기 때문에 연산자의 조합만 구하면 되는데, 
저는 연산자의 조합을 구하고 해당 경우의 수의 연산 결과를 마지막에 도출하는 것이 아니라 연산자를 하나 고를 때마다 연산하도록 하고 이를 재귀 호출할 때 전달했습니다.
✅기저조건
기저조건은 index라는 변수를 사용해 index가 입력되는 숫자의 개수에 도달하면 멈추는 것으로 설정했습니다~~
> 배열을 사용하지 않고 연산자를 관리할 수 있는 방법이 궁금해요~!

w03_연산자 끼워넣기 - 혜선

---

src/main/java/org/example/iroo2001/w03_연산자끼워넣기/Main.java

[백준 14888 - 연산자 끼워넣기](https://www.acmicpc.net/problem/14888)
서로 다른 모든 경우의 수를 구하고, 계산된 수의 최대,최소를 구하는 문제라고 생각했습니다.
연산자가 각각 몇개 남았는지 저장하고, 재귀함수를 통해 모든 경우의 수를 구했습니다.
연산자 남은 개수를 저장할 때, 4개의 변수 혹은 배열을 사용해도 좋지만, 하나의 변수로 관리하기 위해 인코딩과 디코딩을 진행했습니다.
+, -, *, /로 4개의 연산자가 각각 최대 10개까지 저장될 수 있으므로,
각 연산자의 개수는 최대 두자리수를 차지합니다.
++--**// 형식으로 각 연산자 개수를 인코딩하여 하나의 int 변수에 저장했습니다.
(입력이 2 1 3 1인 경우, 02010301로 저장됩니다.)
디코딩은 100^n으로 나눈 몫과 나머지를 활용했습니다.
재귀함수 매개변수 : 남은 연산자 정보, 이전 계산 결과, 현재 계산할 수의 index, 현재 계산할 연산자
재귀함수가 한번 호출되면, 다음 수와 다음 연산자를 활용하여 계산합니다.
남은 개수가 1개 이상인 연산자가 있다면, 다시 재귀함수를 호출하여, 다음 결과를 계산합니다.
현재 계산할 수의 index가 입력으로 주어진 수의 개수 - 1와 같은 경우, 모든 수를 계산했으므로 max와 min에 저장합니다.
괜히 너무 복잡하게 풀이한 느낌..입니다..

w03_연산자끼워넣기 - 이루

---

src/main/java/org/example/seonmin98/w04_로또/Main.java

https://www.acmicpc.net/problem/6603
1. k 개의 수를 갖는 배열 입력 받기
2. 저장한 배열에서 6개의 로또 번호를 선택
2 - 1. 입출력 모두 오름차순이므로 인덱스 순으로 넣고 빼주자!!
2 - 2. idx, lev, list 를 매개변수로 재귀 돌리기!!
2 - 3. lev 이 6에 도달하면 6개가 모두 선택되었으므로 list 출력
2 - 4. idx 가 k 보다 커지면 재귀 종료
> 선택할 번호를 저장할 리스트는 스태틱으로 선언하는 게 좋을까요 인자로 들고 다니는 게 좋을까요?

w04_로또 - 선민

---

src/main/java/org/example/iroo2001/w04_로또/Main.java

[BOJ 6603 : 로또](https://www.acmicpc.net/problem/6603)
1. 입력으로 주어진 수를 배열로 저장
2. Arrays.sort()로 배열 정렬
3. 정렬된 배열로부터 조합 활용하여 6개의 수를 출력
> 
매번 static으로 선언하려니 불안불안한데..
더 복잡한 로직이나 구현 문제가 나올 때를 대비해서 static 사용을 줄일 방법이 있을까요?

w04_로또 - 이루

---

src/main/java/org/example/yhs3237/w04_lotto/baekjoon6603.java

https://www.acmicpc.net/problem/6603
숫자들의 조합을 구하는 문제여서 재귀+백트래킹으로 풀이했습니다. 
사실 양심고백하자면 출력할 때 Collections.sort해야지 했는데 안 했습니다. 그래도 맞은 걸 보니 모든 테스트케이스 입력 자체가 그냥 오름차순으로 주어지나 봅니다....^^
나머지 풀이 내용은 코드 주석으로 대체하겠습니다.

w04_로또 - 혜선

---

src/main/java/org/example/rt8632/w04_Lotto/boj_6603.java

https://www.acmicpc.net/problem/6603
- 백트래킹으로 풀었는데 아직 익숙치 않아서 풀이 참고하면서 풀었습니다 흑흑
- 어려와잉....
- 아직도 재귀가 너무 어려워요 흑흑

w04_로또 - 예린

---

src/main/java/org/example/yhs3237/w05_sugarDelivery/baekjoon2839_dp.java
src/main/java/org/example/yhs3237/w05_sugarDelivery/baekjoon2839_for.java

https://www.acmicpc.net/problem/2839
💫 N에서 3을 뺀 경우와 N에서 5를 뺸 경우를 비교해서 최소값을 설탕 봉지 개수 배열에 저장해야겠다고 생각하고 접근했습니다.
그럼 이 때, 배열에 있는 봉지 개수를 어떻게 가져올 것인가를 생각해보면 
1) 반복문을 사용해 6부터 N까지의 봉지 개수를 저장하고, 배열의 N번째 값을 출력하는 방법
2) 재귀를 통해 찾아오는 방법
💫 저는 이 두가지 방법을 1)은 앞으로 나아가는 방법(i++하면서 N에 다가감), 2)는 과거로 돌아가면서(깊이가 깊어질수록 더 작은 값으로 다가감) 찾아오는 방법이라고 이해했습니다...(야매이해법^^)
💫 처음 생각엔 재귀가 더 효율적이라고 생각해 재귀로 먼저 풀고 반복문을 사용해서도 풀어봤는데 메모리 사용이나 시간이나 비슷하게 나왔습니다.
아마 배열을 생성하고 처음부터 10001로 초기화해서 그런 것 같기도 합니다. 시간은 재귀가 덜 걸릴 줄 알았는데 아니었네용.
> 아직 dp는 첫 아이디어는 떠오르는데 막상 로직을 구현하려고 하면 잘 떠오르지 않아요...ㅠㅜ 그리고 재귀를 사용하면서 반복문에 비해 공간복잡도/시간복잡도를 줄 일 수 있는 방법이 있을까요?

w05_설탕 배달 - 혜선

---

src/main/java/org/example/iroo2001/w05_설탕배달/Main.java

[백준 2839번 : 설탕 배달](https://www.acmicpc.net/problem/2839)
계산식으로도 풀 수 있지만 DP로 풀었습니다.
1. i를 만들기 위해 필요한 봉지 개수를 저장할 배열 만들기
2. 3을 만들거나 5를 만들기 위해서는 1개의 봉지가 필요하므로, 배열에 미리 저장해두기
3. 0, 1, 2, 4를 만드는 것은 불가능하므로, 미리 표시해두기(매우 큰 값으로 표시함)
4. 점화식 세워보기
-> 10을 만들기 위해서는 7을 만들기 위한 개수+1 혹은 5를 만들기 위한 개수+1
-> 7 개수 혹은 5 개수 중, 작은 것을 선택해야 하므로 10을 만들려면 min(dp[5], dp[7])을 해야함
-> 점화식 : dp[i] = min(dp[i-3], dp[i-5]) + 1
5. 예외 처리(N 범위, 불가능한 경우)하고 정답 구하기

w05_설탕배달 - 이루

---

src/main/java/org/example/rt8632/w05_SugarDelivery/boj_2839.java

https://www.acmicpc.net/problem/2839
- DP 어떻게 푸는 지 잘 모르겠어서 그냥 그리디로 풀었습니다 헤헷
- 다른 분들 풀이를 보고.. DP를 이해해보겠습니다....
- 처음 보는 알고리즘 개념을 효율적으로 학습하는 방법이 있을까요? 접근 방식을 잘 못잡겠어요

w05_설탕 배달 - 예린

---

src/main/java/org/example/seonmin98/w05_설탕배달/Main.java

https://www.acmicpc.net/problem/2839
어제 풀고 자려고 했는데 규칙을 못찾아서 자버렸네요....
지각했지만.. 그래도 DP로 풀어냈습니다!!
3, 4, 5 에 초기값 세팅해주고 6부터 N까지 돌면서 N-3, N-5 값을 확인하면 되는 문제였네요 :)
> 규칙을 찾고 점화식을 정의하는 게 너무 어려운데 다른 분들은 어떤 식으로 접근하는지 궁금합니다

w05_설탕배달 - 선민

---

src/main/java/org/example/seonmin98/w05_baseball/Main.java

https://www.acmicpc.net/problem/17281
1. 일단 1번부터 9번 타자의 순서를 가지는 순열 조합 만들기
2. 각 순열별로 얻을 수 있는 점수 계산 -> max 갱신
이렇게 두 가지 파트를 구현해야겠다 라고 생각하고 접근했습니다!
- 순열 조합은 재귀로 path를 들고 다니면서 배열이 다 차면 점수를 계산
- 점수 계산은 2차원 배열에 선수별 타격 결과를 저장해두고 반복문을 돌면서 계산
-> 이게 생각보다 까다로웠는데 크게  다음의 두 가지 문제 때문이었습니다...
- 이닝별로 idx를 초기화하는 이슈 발생!
- 진루 계산할 때 map이랑 우선순위큐로 복잡하게 계산하다가 시간초과 이슈 발생!
+) 이닝별로 아웃카운트가 무조건 하나 들어온다는 게 아니라 있어야 한다고 잘못 읽어서 중간에 삽질함ㅜ
> map이랑 우선순위큐로 계산했을 때 시간 초과가 나는 건 알겠는데 주어진 테케 중 마지막 거만 틀리더라구요... 오류 찾아주실 분 구합니다... 그리고 이렇게 문제가 복잡하고 테케가 하나만 틀릴 때는 디버깅을 어떻게 해야할까요?ㅠㅠ

w05_baseball - 선민

---

src/main/java/org/example/yhs3237/w05_baseball/baekjoon17281.java

https://www.acmicpc.net/problem/17281
로직 짜는데는 얼마 안 걸려서 신나했는데 구현이.......ㅎ
🔁 선수들 타순 정하기 (->순열구하기)
- 1번 선수(인덱스0)가 4번타자(인덱스3)로 고정
- 9번 타자까지 공을 쳤는데 3아웃 X = 이닝 끝나지 않음 = while문 사용 (3아웃 발생할 때까지)
- 선수의 인덱스가 8이 되면 다시 0으로 (% 연산 사용)
💫 순열 만들어지면 그 경우의 점수 계산 (구현)
- 3아웃이면 이닝 종료 : while(out < 3) { }
- 이닝 변경되더라도 타순 유지 : player[inning+1][indx] (반복문 돌면서 inning++, indx는 반복문 밖에서 선언해서 초기화되지 않도록 하기)
- indx로 player[ ][ ]에서 해당 선수의 득점 가져오기 -> 득점에 따라 타자+주자들 이동
- 홈에 선수가 들어오면 += score
- max값 갱신 (Math.max(max, score))
> 이런 구현 문제에서 시간 초과를 줄이려면 어떻게 해야할까요....

w05_baseball - 혜선

---

src/main/java/org/example/iroo2001/w06_소문난칠공주/Main.java

[백준 1941: 소문난 칠공주](https://www.acmicpc.net/problem/1941)
아래 순서에 맞춰 진행했습니다.
I. 문제 요구사항 분석
II. 필요한 정보 정리
III. 구현
I. 문제 요구사항 분석
- 연결되어 있는 7칸을 선택해야한다.
- 하나의 선으로 연결될 필요는 없다(여러 갈래로 나뉠 수 있다).
- 7칸 중, Y가 3칸을 초과하지 않아야 한다.
II. 필요한 정보 정리
- 순서 상관 없이 선택된 7개의 서로 다른 좌표
- 선택된 좌표가 연결될 수 있는지 여부
- 선택된 좌표에 포함된 Y의 개수
- 가능한 경우의 수를 저장할 변수
III. 구현
1. 입력 값을 저장
- 5*5 배열을 펼쳐 25칸의 1차원 배열로 저장
- S와 Y 두가지 값만 존재하므로, boolean 배열로 저장
2. 0~24의 숫자를 7개 선택할 수 있는 조합 생성
- combination 메서드 구현하여, SELECTED 배열에 저장
- SELECTED 배열의 인덱스를 1부터 사용하기 위해 8칸으로 초기화
3. 선택된 조합을 활용하여 칠공주가 결성될 수 있는지 검사
- check 메서드 구현하여 검사
i) 선택된 좌표들이 서로 연결되어있는지 검사 (checkConnected 메서드)
-> 첫 번째 좌표를 Queue에 넣고, 첫 번째 좌표와 연결된 다른 좌표를 찾아내 Queue에 넣음
-> 이런 식으로 연결된 모든 좌표를 찾아 Queue에 넣으며 탐색
-> Queue에 넣을 다른 좌표가 없으면, 모든 좌표를 방문했는지 검사
-> 모두 연결되어있다면, 모두 방문했을 것임
ii) 선택된 좌표 7개 중, …

w06_소문난칠공주 - 이루

---

src/main/java/org/example/rt8632/w05_SugarDelivery/boj_2839.java
src/main/java/org/example/rt8632/w06_KevinBacon6Level/boj_1389.java

https://www.acmicpc.net/problem/1389
- BFS 잘 모르겟어용.... 답 보고 풀었는데 흠 연습을 더 해봐야할거같습ㄴ니당...
- 새로운 알고리즘을 학습할 때 기본 틀은 무조건 외우고 그걸 활용하는 식으로 해야하나요? 뭔가 어떻게 학습해야 하는지 잘 모르겠습니다

w06_케빈 베이컨의 6단계 법칙

---

src/main/java/org/example/yhs3237/w07_hidAndSeek/baekjoon1697.java

https://www.acmicpc.net/problem/1697
인접한 이동 가능 위치가 3개인 bfs로 접근했습니다.
여기서 선택지가 +1, -1. X2 인데 이걸 어떻게 선택하도록 할 것인지에 대한 고민이 있었습니다.
X2 에 대한 델타 배열을 어떻게 만들어야할지 고민했는데, 델타 배열을 bfs의 구현부인 while문 안에 넣어서 만들었습니다.
queue에서 현재 위치인 current를 꺼내오고, current+1, current-1, current*2 하는 식으로 델타 배열을 만들었습니다.
그리고 방문 배열은 K의 최대 범위인 100000+1로 만들어줬습니다.

w07_숨바꼭질 - 혜선

---

src/main/java/org/example/seonmin98/w07_숨바꼭질/Main.java

https://www.acmicpc.net/problem/1697
처음에는 냅다 dfs 로 재귀 돌렸는데 stack overflow 나길래 천천히 다시 읽어보니 bfs 로 풀어야 하는 문제였네요...
아직까지로 언제 dfs / bfs 로 풀어야 하는지 바로 판단이 안서나 봅니다ㅠㅠ 반성합니다....
풀이는 3가지 경우의 수로 나눠서 너비 우선 탐색으로 돌렸고,
따라서 제일 먼저 n == k 되는 순간이 가장 적은 시간에 도달한 값이 됩니다!!
> bfs 로 풀어야 하는 문제임을 단번에 파악할 수 있는 팁이 있을까요?

w07_숨바꼭질 - 선민

---

src/main/java/org/example/rt8632/w07_HideAndSeek/boj_1697.java

https://www.acmicpc.net/problem/1697
- 지피티의 도움을 받은 코드인데 솔직히 왜 카운트를 저렇게 넣어야 하는지는 이해가 잘 가지 않습니다....
- 개념을 모르는 건 아닌거같은데 활용이 잘 안돼요 ㅜㅜ 너무 고통스럽습니다.......

w07_숨바꼭질 - 예린

---

src/main/java/org/example/yhs3237/w07_goSchool/Solution.java

https://school.programmers.co.kr/learn/courses/30/lessons/42898
DP라고 써있지만 뭔가 BFS로도 될 것 같아서 BFS로 풀어봤는데 시간 초과....
굴복하고 DP로 다시 풀었습니다.
초기 설정으로는 물 웅덩이가 있는 곳은 -1로 초기화해서 가지 못하도록 했습니다.
시작점이 있는 곳과 같은 선상에 있는 행과 열을 모두 1로 초기화 ->  -1인 칸은 가지 않도록 함 -> 방문한 칸은 [i-1][j]와 [i][j-1]인 칸을 더한 값으로 갱신 -> 하지만 인접한 곳에 -1이 있다면 둘 중 하나만 더해 줌
처음에 이렇게 풀었더니 답은 맞는데 효율성 평가에서 다 실패했습니다.
그래서 
시작점만 1로 초기화 ->  -1인 칸을 방문하면 넘어가되, 해당 칸은 계산의 편의성을 위해 0으로 갱신 -> 방문하는 좌표를 [i-1][j] + [i][j-1] 값으로 갱신
이렇게 개선했습니다.
시작점만 초기화해도 같은 선상 칸들도 반복문을 돌면서 알아서 갱신되는 걸 몰라서 그냥 첫줄들은 다 초기화를 직접 해버렸네요 😂
> 사실 이 문제는 DP라고 안 써 있었으면 BFS로 계속 시도해서 오래 걸렸을 것 같은데, 문제를 보고 DP로 풀어야 한다!라고 판단하는 기준이 있을까요?

w07_등굣길 - 혜선

---

src/main/java/org/example/rt8632/w07_goSchool/programmers_goSchool.java

https://school.programmers.co.kr/learn/courses/30/lessons/42898
- DP는 아직 문제를 봐도 접근 방식을 잘 모르겠습니다... 그래서 풀이 참고했습니다....
- 점화식을 세우라는데 대체 어떻게 세??우는??건지??? 이해가 1도않되요
- 사람살려
- 너 무 어 려 워
- 이게 문제를 푸는건지 걍 풀이보고 따라치기인지.... 공통 문제 풀때마다 계속 풀이를 보게 되는 것 같아서 자괴감이 듭니다

w07_등굣길 - 예린

---

src/main/java/org/example/seonmin98/w07_등굣길/Solution.java

https://school.programmers.co.kr/learn/courses/30/lessons/42898#
처음에 dfs 로 풀었는데 시간초과가 나서... GPT의 도움을 받아 DP로 다시 풀었습니다..!
1. 물웅덩이의 값을 2차원배열에 저장
2. 시작점(1,1)부터 끝지점(n,m)까지 순회하면서 이전 값들을 활용해 계산
2 - 1. 이 때, 시작점은 1로 초기화해두기
2 - 2. 순회하다가 물웅덩이를 만나면 0 저장
> dp 접근법이 너무 어려운데 막상 코드는 되게 간단하네요.. 역시 이번에도 점화식 생각해는 게 관건이었습니다ㅜ

w07_등굣길 - 선민

---

src/main/java/org/example/yhs3237/w08_lie/baekjoon1043.java

https://www.acmicpc.net/problem/1043
1️⃣ 진실을 아는 사람과 같은 파티에 있거나, 2️⃣진실을 아는 사람과 같은 파티에 갔던 사람과 같은 파티이면 해당 파티에서는 과장을 할 수 없다 
-> 특정 파티에서 과장하려면 위 조건을 만족해야 함
-> 진실 피플들과는 털 끝 하나라도 닿아서는 안 됨
-> 서로소 집합 !
그래서 Union-Find 사용해서 풀었습니다. 
자세한 풀이는 주석으로 달아놓았습니다~!
> 대표자를 판단할 때, 대표자가 진실피플인지 보려고하다보니 3중 for문을 돌리게 되었는데 시간적으로 더 효율적인 방법이 있을까요?

w08_거짓말 - 혜선

---

.idea/misc.xml
src/main/java/org/example/yhs3237/w08_algoSpot/baekjoon1261.java

https://www.acmicpc.net/problem/1261
최단 거리로 가야하면서도 벽을 적게 부수고 지나가야 하는 문제... 
1. 최단거리니까 bfs를 써야겠다
2. 근데 벽을 적게 부숴야 하니까 0과 1을 우선순위를 설정해야겠다 -> Deque에 addFirst(0), addLast(1)로 넣어서 관리
3. 벽을 부순 횟수도 세어야 함... -> 각 좌표가 0이나 1로 주어지니까 이걸 가중치로 두고 dist배열을 만들어서 가중치를 저장
마지막에 dist[N-1][M-1]을 출력하면 벽을 부순 횟수가 출력됩니다
처음에 maze와 dist배열을 1~N, 1~M 범위로 설정했더니 input.charAt(index) 할 때 인덱스 오류가 나더라구요...?
그래서 그냥 0부터로 수정했읍니다...
> 다익스트라를 써서 푸는 방법도 있다던데 도저히 떠오르지 않아요... 혹시 다익스트라로 푸신 분...?

w08_알고스팟 - 혜선

---

src/main/java/org/example/seonmin98/w08_알고스팟/Main.java

https://www.acmicpc.net/problem/1261
0. 최단거리니까 bfs로 풀면 되려나? 했는데 돌아가서라도 벽을 적게 뚫는 경우가 있으므로 안되겠군...
1. 그렇다면 이번주에 배운 다익스트라 알고리즘을 적용해보자!
2. 근데 그래프가 아니라 2차원배열이네...어떻게 적용하는 거지...하다가 그냥 2차원 배열 순회 돌렸는데 테케 돌아가길래 제출했더니 fail...
3. 탐색할 때 순회가 아니라 bfs를 쓰면 되겠다! 계산 귀찮으니까 우선순위큐에 다 넣고 방문처리해야지~
뭔가 돌아돌아 간 느낌이네요ㅠㅠ
> 다익스트라 적용할 거면 사실 방문배열이 필요없고 넣어줄 때 최솟값만 넣어주는 게 맞는 것 같긴 한데... 최솟값 계산하는 로직이 아직 익숙치 않아서 이렇게 풀게 되네요...ㅠㅠ 그래도 방문매열 안쓰는 걸로 익혀두는 게 좋으려나요?

w08_알고스팟 - 선민

---

src/main/java/org/example/rt8632/w08_Lie/boj_1043.java
src/main/java/org/example/rt8632/w09_AlgoSpot/boj_1261.java

https://www.acmicpc.net/problem/1261
- BFS + 다익스트라.. 인데 다익스트라를 어떻게 쓰는지 잘 모르겠어서 풀이 참고했습니다
- 클래스 선언하기 싫어서 우선순위 큐 내에 배열을 선언했는데 저 Comparator.comparingInt(a -> a[2])를 사용하면 벽을 덜 부순 순으로 정렬이 된다고 하네요....
- 다익스트라 연습하기 좋은 문제가 있을가요?

w09_알고 스팟 - 예린

---

src/main/java/org/example/seonmin98/w09_동전문제/Main.java

https://www.acmicpc.net/problem/9084
dp로 풀어야겠다는 건 알겠는데 괜히 복잡하게 생각해서 한참 헤맸습니다..ㅜ
> 동전의 종류가 1원, 2원이고 목표금액이 1000원일 때
> 1원으로 만들 수 있는 1000원의 종류도 하나 (1원 * 1000)
> 2원으로 만들 수 있는 1000원의 종류도 하나 (2원 * 500)
> 근데 1원 + 2원으로 만들 수 있는 1000원의 종류를 생각하면 너무 복잡해짐... 1원 998개, 2원 1개 ...
근데 그냥 dp를 0원부터 목표금액까지 만들고 각 동전마다 0원부터 목표금액까지 dp를 돌리면 되는 거였네요...!! (머리 안돌아가서 gpt한테 힌트 받아서 풀었습니다ㅠㅠ)
> 그래도 동전이나 배낭..? 정도는 이제 점화식 어떻게 세우는지 대충 감은 잡히는데 그래도 어렵네요흑흑 처음보는 디피유형은 감도 못잡을 것 같아여....

w09_동전문제 - 선민

---

src/main/java/org/example/rt8632/w09_Coin/boj_9084.java

https://www.acmicpc.net/problem/9084
- gpt와 풀이의 도움으로 점화식을 이해해보앗습니다...
- 근데 넘 어려워요 흑흑
- dp는너무어려워..................................

w09_동전 - 예린

---

src/main/java/org/example/yhs3237/w09_setRouter/baekjoon2110.java

https://www.acmicpc.net/problem/2110
문제 이해하는데만 20분 걸린 것 같아여....
최소값들 중 최대값을 구하는 따뜻한 하지만 얼음을 넣은 아메리카노 같은 문제...
일단 인접한 공유기 간의 거리의 최소값이 최대가 되게 하려면 극단적으로 멀거나 극단적으로 가까우면 안 되기 때문에 최대한 균등하게 분배하는게 포인트라고 생각했습니다.
그러면 이제 이분 탐색인데... 
1) 이분 탐색을 mid = (첫번째 집과 마지막 집의 거리)/2 로 시작을 했고, 이게 인접한 공유기 간의 최소 거리가 되어야 하기 때문에 그 다음에 배치할 때는 전체 집들을 탐색하면서 mid<= 인 거리로만 배치(count++)했습니다.
2) 전체 집을 모두 탐색하면서 배치한 결과(count의 값)가 C보다 크면 mid보다 더 먼 거리로 해도 된다는 뜻, C보다 작으면 mid보다 짧은 거리로 조정해야 한다는 뜻이므로 if문으로 값을 조정해주었습니다.
3) 그리고 이분탐색의 경우, start가 end와 교차되면 멈추어야 하므로 while (start <= end)로 정지 조건을 설정하였습니다.
> 시간 제한이 2초인데 이 문제를 조합 문제로 풀면 시간 초과가 될까요...? 집의 개수가 최대 20만이라 뭔가 그럴 거 같기도 한데 시도해본 사람이 있는지 궁금하네요...!

w09_공유기 설치 - 혜선

---

src/main/java/org/example/seonmin98/w09_공유기설치/Main.java

https://www.acmicpc.net/problem/2110
이분탐색으로 풀어보려 했으나,,, 코드설계를 못 하겠어서 일단 조합으로 풀었는데 시간초과 이슈발생,,,
> 아직도 언제 시간초과가 나는지 계산을 못하네요,,,꿀팁 알려주실 분 ㅠㅠ

w09_공유기설치 - 선민

---

src/main/java/org/example/yhs3237/w10_escape/baekjon3055.java

https://www.acmicpc.net/problem/3055
물도 이동하고 고슴도치도 이동하는 문제로 bfs를 while문 안에서 2개를 써야하는 문제입니다!
물이 먼저 이동하기 때문에 물을 먼저 bfs로 영역을 확장하도록 해주고, 고슴도치가 이동할 수 있는지&가능하다면 최단거리는 어떻게 되는지를 bfs로 계산해주었습니다.
뭔가 이거 풀고 나니까 배틀싸피랑 비슷했다는 느낌도 드네요...? 이거 주말에 풀어볼걸 ㅠ

w10_탈출 - 혜선

---

src/main/java/org/example/seonmin98/w10_탈출/Main.java

https://www.acmicpc.net/problem/3055
BFS로 최단거리 구하는데 물확장을 고려해야 하는구나!! 로 접근했습니다.
첫번째 시도) 2%에서 실패
: 물 확장할 때 2차원 배열 순회하면서 물 만나면 상하좌우로 확장해버려서 당장 추가한 물을 기준으로도 확산이 되어버리는 이슈발생
두번째 시도) 45%에서 실패
:  물이 찰 예정인 곳으로 이동 불가하는 예외 처리에서 첫 시작점을 고려하지 못한 이슈발생
세번째 시도) 드디어 성공~!~!
> 물 확장하는 코드를 요상하게 짠 것 같은데 ㅋㅋㅋㅋ 아직 BFS와 덜 친해졌나봅니다... 얼른 다른 분들 코드 참고해서 공부하겠습니다!
> 그리고 테케가 너무 구린데... 주어진 테케는 다 맞았는데 계속 틀리는 경우 다양한 경우의 테케를 직접 만들어 넣어보는 연습도 필요할까요?

w10_탈출 - 선민

---

src/main/java/org/example/rt8632/w10_Escape/boj_3055.java
src/main/java/org/example/rt8632/w10_Escape/boj_3055_v2.java

- map, water, gosumdochi 2차원 배열을 다 따로 만들고 값을 비교하는 방식으로 했는데, 접근 방식 자체는 나쁘지 않았다고 생각하는데 로직 구현에서 너무 헤매서 170줄이 넘는 어메이징 코드가 탄생해버렸습니다... 디버깅을 2시간 했는데 결국 반례 해결을 못해서 gpt 수정본도 같이 첨부합니다.
- ㅎ ㅏ................................ 너무힘들었어요..................................

w10_탈출 - 예린

---

src/main/java/org/example/yhs3237/w10_palindrome/baekjoon1213.java
src/main/java/org/example/yhs3237/w10_palindrome/baekjoon1213_backtracking.java

https://www.acmicpc.net/problem/1213
첨에 백트래킹해서 순열 구하고 그 경우가 팰린드롬에 해당하는지 검사해서 정답 리스트에 넣고 정렬해서 첫번쨰 걸 출력하는 방법으로 풀었습니다.
tc 사이트에서도 반례 하나도 없다고 나와서 신난다 하고 제출했는데 1%에서 시간초과....ㅎ
(하지만 백트래킹 코드 아까워서 같이 커밋해봤읍니다 ^________________^)
시간 줄이는 방법은 도저히 모르겠어서 지피티에게 물어봤습니다.
근데 팰린드롬의 구성 조건이 있더라구요....?
⭐🌟💫🌠팰린드롬의 구성조건🌠🌟💫⭐
1. 문자열의 길이가 짝수인 경우, 모든 문자가 짝수개여야 함
2. 문자열의 길이가 홀수인 경우, 한 문자 빼고는 모든 문자가 짝수개여야 함
그리고 이 구성조건에 맞는다면, 홀수번 등장한 알파벳을 mid(중간 문자)로 잡아주고 나머지 문자열로 절반 부분에 해당하는 문자열을 만들어줍니다.
그리고 만약에 문자열의 길이가 짝수이면 mid가 없을 것이므로 그냥 절반 부분 문자열을 reverse해서 붙여주면 되고
문자열의 길이가 홀수이면 mid가 있을 것이므로 절반 부분 + mid + 절반 부분 문자열 reverse 해주면 됩니다!
> 그리디 알고리즘은 딱 보고 어떻게 풀어야 할지 생각해내는 게 넘 어려운 것 같아요... 냅다 다른 방법으로 했다가 답은 맞는데 시간이나 공간복잡도가 아주 비효율적이게 되는 경우가 많은 것 같아요ㅠ 이런 경우에는 어떻게 문제 해결 방법을 생각해내시나요 다들

w10_팰린드롬 만들기 - 혜선

---

src/main/java/org/example/seonmin98/w10_팰린드롬만들기/Main.java

https://www.acmicpc.net/problem/1213
1. 카운팅배열을 하나 만들어 알파벳 대문자의 개수를 저장
2. 'A'부터 'Z'까지 순회하면서 앞뒤로 각각 큐, 스택에 두 개씩 묶어서 넣어주기
2-1. 이때 홀수면 한개가 남는데, 팰린드롬의 경우 이 홀수는 단 하나의 알파벳만 존재해야 됨!!
2-2. 따라서 홀수인데 이미 홀수인 알파벳이 저장되어 있는 경우 바로 불가능문자 출력하고 리턴
3. 문제 없이 순회를 완료한 경우, FRONT - MID - BACK 순서로 뽑아서 출력~~
> 아직 자바에서는 char랑 String을 잘 활용하는 법을 모르겠습니다.. 
> 이 부분 관련해서 개선할 부분이 있다면 알려주세요!!

w10_팰린드롬만들기 - 선민

---

src/main/java/org/example/rt8632/w10_MakePalindrome/boj_1213.java

https://www.acmicpc.net/problem/1213
- 저도 백트래킹으로 풀엇다가 메모리초과낫더염
- 망함
- 다시풀게요........
- 어려워어어어어어어억

w10_팰린드롬 만들기 - 예린

---

src/main/java/org/example/yhs3237/w11_rollDice/baekjoon14499.java

https://www.acmicpc.net/problem/14499
첨에 주사위 배열을 하나만 만들어두고 현재 밑면과 방향에 따라 새로운 밑면을 갱신해주면서 주사위를 굴렸는데 같은 방향으로 계속 이동할 땐 오류가 없는데 방향이 전환되자마자 값에 오류가 생기더라구요ㅠ
그래서 지피티에게 물어봤는데 주사위 각 면에 넘버링을 해두고 밑면에 n번면이 온다!라고 생각했던게 틀렸다고 하더라구요...?
각 면에 넘버링을 해두었다고 생각하지만 사실은 방향에 따라 밑면에 오는 n번면이 달라져서 그렇다고 함니다....
그래서 원본 dice 배열은 그대로 두고(1번-윗면, 6-밑면 ...) dice 배열을 복사해서 그 배열의 값을 변경해서 그걸 원본 dice 배열에 넣어주는  방법으로 바꿨읍니다.
나머지 부분은 그냥 if문으로 처리하는 거라 코드 내 주석으로 대체하겠습니다!
> 사실 아직도 주사위가 돌아가는 방향이 달라질 때마다 넘버링 된 면이 고정된 것이 아니라 계속 바뀐다는 부분이 잘 이해가 가지 않아요ㅠ 이해하신 분이 있다면 도와주세요~~!!

w11_주사위 굴리기 - 혜선

---

src/main/java/org/example/seonmin98/w11_주사위굴리기/Main.java

https://www.acmicpc.net/problem/14499
주사위를 top, bottom, left, right, front, back 배열로 관리
--> 동서남북 별로 6면이 어떻게 바뀌는지 파악해서 방향별로 함수 만들기
--> 인덱스를 벗어나면 아무 동작 하지 않고 바로 리턴
--> 인덱스 범위 안에 있다면 1. 주사위 바꾸기 2. map이랑 비교해서 업데이트 3. top 출력
(디버깅용 코드 주석안하고 제출해서 한번 fail....)
> 역시 구현 문제 재밌네요ㅎㅎ 뭔가 더 정돈해서 리팩토링할 수 있을 것 같은데 코테 풀 때는 일단 구현 먼저 하는 게 나을까요? 아니면 코테 풀 때에도 처음부터 더 효율적인 설계를 고민해서 코드를 작성해야 할까요?

w11_주사위굴리기 - 선민

---

.idea/gradle.xml
.idea/inspectionProfiles/Project_Default.xml
.idea/misc.xml
src/main/java/org/example/rt8632/w11_RollTheDice/boj_14499.java

https://www.acmicpc.net/problem/14499
- ㅎ ㅏ 메인에 잘못 올려서 다시 올립니다...
- 주석 달아두엇습니다...
- 테케가 틀렷어요 힝 내일 다시 풀게요

w11_주사위 굴리기 - 예린

---

src/main/java/org/example/yhs3237/w11_hacking/baekjoon10282.java

https://www.acmicpc.net/problem/10282
풀이 내용은 주석으로 대체하겠습니다.

w11_해킹 - 혜선

---

src/main/java/org/example/seonmin98/w11_해킹/Main.java

https://www.acmicpc.net/problem/10282
다익스트라 알고리즘의 정석!!
(마감기한에 쫓겨 수업 내용 참고해서 풀었습니다..ㅜ)
> 오랜만에 다익스트라 알고리즘 복습할 수 있는 시간이어서 좋았습니다! 주말에 다시 한번 풀어봐야겠네요~ 근데 또 다른 사람 계정으로 push 해버림...죄송함다.......

w11_해킹 - 선민

---

src/main/java/org/example/rt8632/w11_Hacking/boj_10282.java

https://www.acmicpc.net/problem/10282
- 완전히 다익스트라....의 정석같은 문제네요
- 따봉지피티야고마워

w11_해킹 - 예린

---

src/main/java/org/example/yhs3237/w13_searchCourse/baekjoon1504.java

https://www.acmicpc.net/problem/1504
1. 다익스트라인데 조건을 곁들인... 이라서 처음에는 조건을 여러개 줘 봤읍니다. 일단 꼭 거쳐야 할 정점을 우선순위로 하되 여러 개면 cost가 더 작은 곳으로 가게...했는데 이렇게 하고 다익스트라를 했더니 cost배열을 만들어가는 과정에서 어차피 최소 거리인 애를 갱신해주다보니 아주 쓸모가 없었습니다.
2. 결국에는 꼭 거쳐야할 정점을 무조건 지나서 N으로 가는 두가지 경우의 수를 상정하고 다시 로직을 만들었습니다.
두가지 경우의 수는 1 -> v1 -> v2 -> N 이거나 1 -> v2 -> v1 -> N 입니다.
3. 그리고 두번째 조건은 최단 거리로 가는 것이기 때문에 각 구간별 최단 거리를 다익스트라를 통해 구해주었습니다. 
4. 구간 별 최단 거리를 구할 때, 만약 해당 구간의 cost[end] 값이 갱신되지 않았다면 도달할 수 없다는 뜻이므로, 예외 처리를 해주어야 합니다. 각 구간의 값이 하나라도 Integer.MAX_VALUE인 경우 어떻게 해도 위 조건을 만족하면서는 도달할 수 없기 때문에 -1을 출력해주고 그 이외에는 각 경우의 수 별로 구간 합을 모두 더해 2가지 중 최소값을 출력해줍니다.
> 뭔가 다 풀고나니까 다익스트라보다 dp로 푸는 게 나을 것 같다는 생각도 드는데 혹시 dp로 시도해본 분이 계실까여

w13_특정한 최단 경로 - 혜선

---

src/main/java/org/example/seonmin98/w14_토마토/Main.java

https://www.acmicpc.net/problem/7569
3차원 배열이라는 점을 제외하면 평범한 bfs 문제였습니다!
날마다 익은 토마토 -> 안익은토마토로 앞뒤위아래좌우 6방향으로 한칸씩만 익히면 끝~
> 너비우선탐색과 3차원 배열 두 개념을 익히기 좋은 문제네요:)

w14_토마토 - 선민

---

src/main/java/org/example/yhs3237/w14_tomato/baekjoon7569.java

https://www.acmicpc.net/problem/7569
처음으로 3차원 배열을 써봤습니다....
처음에는 그냥 2차원 배열에 층 수를 한 층의 가로 수로 해보려고 했는데 오류가 났읍니다.
```
dr = new int[] {N, -N, 0, 0, -1, 1};
dc = new int[] {0, 0, -1, 1, 0, 0};
```
이렇게 델타배열을 선언해서 사용하려고 했는데 인덱스에 문제가 있는지 오류가 나서 3차원 배열로 재시도 했습니다.
3차원 배열로 시도한 부분 말고는 일반적인 bfs 풀이 방법으로 풀었습니다~~

w14_토마토 - 혜선

---

src/main/java/org/example/rt8632/w14_Tomato/boj_7569.java

https://www.acmicpc.net/problem/7569
- 3차원 배열에 BFS 써서 풀었습니다
- 흠 3차원 배열 말고는 다른 풀이가 없을까요?

w14_토마토 - 예린

---

src/main/java/org/example/seonmin98/w14_가장긴짝수연속한부분수열/Main.java

https://www.acmicpc.net/problem/22862
투 포인터라는 건 알겠는데... 
첫번째 시도: start = 0, end = N-1 로 시작해서 양쪽에서 가운데로 범위 좁히기
두번째 시도: start = (N / 2) -1 , end = (N / 2)로 시작해서 가운데에서 양쪽으로 범위 확장하기
로 시도하다가 제대로 된 풀이법을 못찾겠어서 GPT에게 힌트 얻고 풀었습니다..ㅜ
start = 0, end = 0 으로 둘다 처음부터 시작해서 end 로 범위 확장해주되,
홀수인 경우 카운트 해주고,
만약 카운트가 다 찼을 경우 -> start를 땡겨오는 식으로 계산하면서
현재 구간에서의 연속한 짝수의 수를 계속 갱신해주는 식으로 풀었습니다!
> 역시 익숙하지 않은 투포인터...아직 낯설고 어렵네요ㅠㅠ start랑 end 초기값을 다르게 설정해서 풀이하는 방법도 있는지 궁금합니다!

w14_가장긴짝수연속한부분수열 - 선민

---

src/main/java/org/example/rt8632/w14_LongestSubsequenceLarge/boj_22862.java

https://www.acmicpc.net/problem/22862
- 따봉지피티야고마워
- 투 포인터 자체는 이해가 되는데 문제를 이해하기가 어려움..... 무슨말이지 이게?
- retry를하겟다고 선언.

w14_가장 긴 짝수 연속한 부분 수열(large) - 예린

---

src/main/java/org/example/yhs3237/w15_marbles/baekjoon13460.java

https://www.acmicpc.net/problem/13460
조금 조건이 많은 BFS 느낌...? 
빨간 구슬과 파란 구슬은 반대로 움직인다는 점을 생각하고 델타배열을 반대로 움직여주는 것과 파란 구슬이 구멍에 들어가면 실패한다는 조건 & 10번이 넘어가면 실패한다는 조건을 잘 염두하고 bfs 코드를 짜면 되는 문제였습니다.
크게 어렵지 않은 문제여서 나머지 풀이는 주석을 참고해주세요~

w15_구슬 탈출2 - 혜선

---

src/main/java/org/example/yhs3237/w15_startLink/baekjoon14889.java

https://www.acmicpc.net/problem/14889
1) 조합&반대조합 구하기 
2) 조합으로 나온 숫자를 가지고 능력치의 합 구하기 & 반대 조합의 숫자로도 능력치의 합 구하기
3) 합의 차 구해서 최소가 되도록 하기
백트래킹을 오랜만에 했더니 조합 구하는 방법도 넘 헷갈렸습니다ㅠ
그리고 반대조합을 어떻게 구해야 할까 고민을 많이했는데, Hashset을 써야하나 하다가 그냥 boolean 배열로 방문 표시만 해주고 정지조건 부분에서 팀을 조합해주었습니다.
그리고 인덱스 조절해주는 부분에서도 고르는 숫자랑 인덱스가 달라서 오류가 난 부분이 조금 헷갈리기도 했습니다...
> 다들 반대조합 구할 때 어떤 방식을 사용하시나요!?

w15_스타트와 링크 - 혜선

---

src/main/java/org/example/seonmin98/w15_스타트와링크/Main.java

https://www.acmicpc.net/problem/14889
1. N / 2 만큼 pick하는 조합 구하기
2. 조합이 완성되면 이중 for문 돌면서 각 팀별 능력치 계산 -> 최솟값 갱신
> 이중 for문 도는 방법 말고 좀 더 효율적인 방법이 있을지 궁금합니다!

w15_스타트와 링크 - 선민

---

src/main/java/org/example/yhs3237/w16_stringExplosion/baekjoon9935.java

https://www.acmicpc.net/problem/9935
어떤 자료구조로 풀까 고민하다가... 덱을 써볼까 고민하다가 굳이 어려운 자료구조로 안 해도 되겠다는 생각이 들어서 리스트로 해보았습니다.
인덱스가 조금 헷갈리긴 하지만 잘 맞춰주면 오류없이 잘 결과가 나옵니다!
특히, list에서 문자들을 지울 때 역순으로 리스트의 끝에서부터 지워주는 것이 중요합니다.
> 덱을 쓰면 더 편할 거 같은데 아직 익숙하지가 않아서 그런가 손이 잘 안가네요... 혹시 덱으로 푸신 분이 있을까요~~? 시간복잡도, 공간복잡도 비교해보고 싶네요...!

w16_문자열 폭발 - 혜선

---

src/main/java/org/example/seonmin98/w16_문자열폭발/Main.java

https://www.acmicpc.net/problem/9935
처음에는 indexOf랑 subString 을 활용해봤는데 메모리초과가 나서... 스택을 활용하는 방식으로 다시 접근했습니다ㅠㅠ
> 메서드를 사용함에 있어 메모리 공간을 얼만큼 사용하는지도 유의해야겠네요!

w16_문자열 폭발 - 선민

---

src/main/java/org/example/yhs3237/w17_noDuplication/baekjoon20922.java

https://www.acmicpc.net/problem/20922
투포인터를 복습하기 좋은 문제였던 것 같습니다!
투포인터를 만들어 포인터를 이동시키며 start와 end 포인터 범위 안에서 동일한 숫자가 몇번 등장하는지 세어주고 만약 같은 숫자가 K번 이상 등장한다면 포인터를 조정하여 수열의 길이를 조절해줍니다.
이걸 end(먼저 이동하는 포인터)가 수열의 범위 끝까지 갈 때까지 반복해주었습니다.
> 문제를 보자마자 투포인터인지 알아채기가 조금 오래 걸렸습니다...! 범위를 이동하면서 배열을 탐색하는 문제는 무조건 투포인터다!하고 푸는 게 맞을까요?

w17_겹치는 건 싫어 - 혜선

---

src/main/java/org/example/rt8632/w17_NoDuplication/boj_20922.java

https://www.acmicpc.net/problem/20922
- 처음에 start 범위 조정하고 end 늘리는 방식으로 했는데 이러니까 end 범위가 요상해져서... end를 늘리고 start는 중복 넘어갈때 줄여주는 방식으로 고쳣습니다
- 투포인터는어려워

w17_겹치는 건 싫어 - 예린

---

src/main/java/org/example/yhs3237/w17_oneTwoThree/baekjoon9095.java

https://www.acmicpc.net/problem/9095
보니까 전에 풀었던 문제더라구요....?
어차피 dp 까먹어서 다시 풀어봤습니다...!
dp는 규칙을 찾아 점화식을 세우는게 포인트라고 생각해서 1을 만드는 경우, 2를 만드는 경우, 3을 만든느 경우를 가지고 어떻게 4를 만들 수 있을지를 중점적으로 생각했습니다.
항상 dp는 점화식 세우는 데에 너무 오래 걸리네요ㅠㅜ

w17_1,2,3 더하기 - 혜선

---

src/main/java/org/example/seonmin98/w17_123더하기/Main.java

https://www.acmicpc.net/problem/9095
간단한 DP 문제였습니다!
N의 값 11보다 작은 양수이기 때문에 dp[0]=1을 기반으로 11까지 dp[i] = dp[i-1] + dp[i-2] + dp[i-3]을 구하면 끝!
> dp문제 오랜만이었는데 복습하기에 딱 좋은 문제였습니다 :)

w17_123더하기 - 선민

---

src/main/java/org/example/yhs3237/w18_chicken/baekjoon15686.java

https://www.acmicpc.net/problem/15686
A개 중 B개를 고르는 경우의 수(조합)를 구해서 각각의 경우의 수에서 치킨 거리의 최소값을 구해주는 문제였습니다!
치킨집 중 M개를 고를 때 이걸 어떻게 표시해야 할지를 가장 고민했는데, 저는 치킨집의 좌표를 list에 저장하고 치킨집을 골랐는지 여부는 boolean 배열을 사용해 표시하여 배열의 인덱스를 활용해 치킨집 좌표를 가져오는 방법을 택했습니다.
이외에는 일반적인 백트래킹 코드였고, 각 경우의 수에서 치킨 거리를 구하는 식을 잘 작성하는 것이 포인트였던 것 같습니다!
> 리스트와 boolean 배열 외에 치킨집을 고르는 것을 표시+가져올 때 어떤 자료구조를 사용할 수 있을까요!?

w18_치킨 배달 - 혜선

---

src/main/java/org/example/rt8632/w18_ChickenDelivery/boj_15686.java

https://www.acmicpc.net/problem/15686
- 첨에 감 못잡다가 백트래킹으로 풀엇슴미다
- 근데 넘 헷갈려용 흑흑 어려와잉

w18_치킨 배달 - 예린

---

src/main/java/org/example/yhs3237/w18_cuttingLAN/baekjoon1654.java

https://www.acmicpc.net/problem/1654
전형적인 이분 탐색 문제인데 포인트는 각 변수의 자료형 설정인 것 같습니다!
이분 탐색을 위한 변수를 설정할 때 int로 설정하면 오버플로우가 발생해서 long으로 설정해줘야 하네요!
나머지 자세한 풀이는 주석으로 대체하겠습니다!

w18_랜선 자르기 - 혜선

---

src/main/java/org/example/seonmin98/w18_랜선자르기/Main.java

https://www.acmicpc.net/problem/1654
보자마자 이진탐색임을 알았는데
while문에서 벗어났을 때의 정답이 start 인지 end 인지가 헷갈려서 가능한 최댓값을 변수에 따로 저장했습니다!
그리고,,, 계속 int로 시도하다가 제출을 꽤많이 해버렸습니다,,,ㅜ

w18_랜선 자르기 - 선민
